#pragma once
#include "ParticleBase.h"
#include "AllPolicyNameList.h"
#include "ParticleEmitter.h"
#include "PrtColor.h"
#include "PrtLife.h"
#include "PrtRotate.h"
#include "PrtSize.h"
#include "PrtStartPosition.h"
#include "PrtVelocity.h"
#include "PrtTexture.h"
#include "ParticleManager.h"
#include "ParticleEmitterBehavior.h"
#include "ParticleEmitterGroup.h"
using namespace FATMING_CORE;