#pragma once


enum eFishGameEventMessageID
{
	eFGEMI_CAMERA_CHOCK = 0,
	eFGEMI_STOP_GENERATE_MONSTER,
	eFGEMI_SCENE_CHANGE,
	eFGEMI_FISH_GROUP_GO,
	eFGEMI_FISH_GROUP_FINISH,
	//for hardware register
	eFGEMI_REGISTER_IN,
	eFGEMI_REGISTER_OUT,
	eFGEMI_MAX,
};