#pragma once


#define LEVEL_CHANGE_REACH_MAX_STAY_TIME			1.5f

#define	SHOW_IO_ERROR_WAIT_TIME						0.5f
#define	PRESS_BUTTON_ADD_SCORE_LIMIT_SHOW_MPDI_TIME	5.f

#define	ALLOW_TO_SHOT_BULLET_COUNT					10


#define	ALL_FISH_NOT_IN_SCENE_CHANGE_TO_SCENEB_TIME	5.f

#define	CHANG_SEN_IO_MODE							1
#define	TWLEADSTREAM_IO_MODE						3

#define	REFUND_MODE_COIN							0
#define	REFUND_MODE_TICKER							1
#define	REFUND_MODE_PRINT							2