#ifndef ALL_PHASE_NAME_H
#define ALL_PHASE_NAME_H

#define	WALKING_IN_MAP_PHASE	L"WALKING_IN_MAP_PHASE"
#define	BATTLE_PHASE			L"BATTLE_PHASE"
#define VIEW_MAP_PHASE			L"MAP_PHASE"
#define MAIN_MENU_PHASE			L"MAIN_MENU_PHASE"

#endif